declare var canvas: HTMLCanvasElement;
declare var crc2: CanvasRenderingContext2D;
declare var speed: number;
declare var h: number;
declare var linien: boolean[];
declare let x: number[];
declare let y: number[];
declare function draw(): void;
declare function scrollFunction(): void;
declare function line(x: number, y: number, x2: number, y2: number): void;
declare function animate(): void;
